### ISSUE TITLE
Update `swanky check`

### ISSUE THREAD

**Issue by codespool** [inkdevhub/swanky-cli#114]
# Overview (What and Why)

`swanky check`'s output should simply list all the dependencies' versions, and list the eventual missing ones.
It should also include the OS and architecture info.

The output should also be optionally stored in a file, so it can be shared for debugging purposes  

We should also maintain a remote compatibility list of `cargo-contract version` -> `min ink! version` that should be fetched and used when checking the local env, and warn the user to update the ink! version accordingly

# How

- [x] modify the command output to include install status and versions of all dependencies, including OS
- [x] add optional file output
- [x] host a cargo-contract -> ink dependency table
- [x] fetch and store the dependency table on `init` and `check` use
- [x] check local `cargo-contract` and contract's ink! versions against the table and warn user to update if needed

# Definition of Done

- [ ] above implemented and merged
- [ ] docs updated

# Open Issues and Blockers

**Comment by shunsukew** [comment]
Why not just use redirecting output `swanky check > result.txt` or use copy&paste?
I don't see any value for saving option.
