### ISSUE TITLE
Use issue forms in the swanky repos

### ISSUE THREAD

**Issue by andabak** [inkdevhub/swanky-cli#149]

**Comment by shunsukew** [comment]
Could you elaborate more about this?
We have issue templates.

**Comment by shunsukew** [comment]
Could you elaborate more about this?
We have issue templates.

**Comment by codespool** [comment]
Using the form to report issues seems like the best way to enforce the standardised format.
(changed the title)
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
