### ISSUE TITLE
Add `swanky node version` or equivalent

### ISSUE THREAD

**Issue by HCastano** [inkdevhub/swanky-cli#177]
I know you can see it when you run the node, but I'd like an easy way to find the version of the node installed by `swanky node install`.

This can either be in the form of something like `swanky node version`/`swanky node --version` or shown as part of the `swanky check` command.

**Comment by codespool** [comment]
Great idea, thanks for reporting!
I'm adding it to the suggestions list for the next milestonel

**Comment by codespool** [comment]
This can go together with #135 , I'll close that one, pasting the contents here: 

```
In node install command, having version locking mechanism, and allow users specify which version to install with command args.
```
