### ISSUE TITLE
add a `clear` command

### ISSUE THREAD

**Issue by codespool** [inkdevhub/swanky-cli#179]
# Overview (What and Why)

A `clear` command should be available to remove all the artifacts and build cache

# How

- [x] implement the clear command
- [x] command clears all the artifacts, test artifacts, cargo target directory

# Definition of Done

- [ ] above changes merged and released
- [x] docs updated

# Open Issues and Blockers

**Comment by vsofiya** [comment]
https://github.com/inkdevhub/swanky-cli/pull/189
