### ISSUE TITLE
Improved Config Feature

### ISSUE THREAD

**Issue by andabak** [inkdevhub/swanky-cli#62]
# Overview (What and Why)

Currently no swanky commands can be invoked outside of a swanky project folder.
For some commands that doesn't make sense and they should be available globally.
Since the check consist only of looking for the `swanky.config.json` in current folder, the config should be moved to the OS level config folder, and if needed combined with the local one. (also check the ancestor folders)
Additionally, keys and addresses can be stored in the .env file so that too should be checked
Lastly, a default account should be set, so it doesn't need to be passed every time.

Plus:
- limit dev accounts to interaction only with local/test networks #22 

# How

- [X] Implement a base class to handle config checks and logic 
- [x] Store part of the config to the OS level config dir
- [x] Read the global, local (including ancestor dirs), and .env file and merge them
- [x] Add a default account feature
- [x] Limit dev account interaction

# Definition of Done
{Write definition of done, how to verify}

- [x] Above features are implemented and merged

# Open Issues and Blockers

**Comment by codespool** [comment]
also support .env file, add precedence, local env -> swanky config -> global swanky config

**Comment by codespool** [comment]
Base class feature is already implemented in #71 
What's left is to update the commands to use it.
